version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_lenguas
    # No exponemos puerto al exterior, solo se usa internamente
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_lenguas
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=BibliotecaLenguasModernas
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8085:8080" # <-- Puerto expuesto. Tu Nginx Proxy apuntará a este puerto 8085

volumes:
  mongodb_data:
