version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_lenguas
    # No exponemos el puerto 27017 al exterior para evitar choques con otros proyectos
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_lenguas
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=BibliotecaLenguasModernas
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongodb
    restart: unless-stopped
    # No exponemos el puerto 8080 al exterior, el frontend se conectará internamente

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_lenguas
    ports:
      - "8085:80" # El puerto 8085 de tu VPS apuntará al 80 de este frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
